// convex/schema.ts
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
   //*** USERS ***//
  // Mirrors the Better Auth user — created/updated on sign in
  users: defineTable({
    // Better Auth user id — used to link sessions to users
    authId:       v.string(),
    name:         v.string(),
    email:        v.string(),
    image:        v.optional(v.string()),
    createdAt:    v.number(),            
  })
    .index("by_authId", ["authId"])
    .index("by_email", ["email"]),


  //----SESSIONS ----
  // One row per interview attempt
  sessions: defineTable({
    userId:       v.id("users"),         // who ran the interview
    role:         v.union(               // target role
                    v.literal("fullstack"),
                     v.literal("frontend"),
                    v.literal("backend"),
                    v.literal("devops"),
                    v.literal("mobile"),
                    v.literal("data"),
                    v.literal("systems"),
                    v.literal("cloud"),
                  ),
    level:        v.union(               // experience level
                    v.literal("junior"),
                    v.literal("mid"),
                    v.literal("senior"),
                  ),
    mode:         v.union(               // interview type
                    v.literal("behavioral"),
                    v.literal("technical"),
                    v.literal("mixed"),
                  ),
    status:       v.union(               // lifecycle state
                    v.literal("setup"),       // not started yet
                    v.literal("active"),      // interview in progress
                    v.literal("completed"),   // finished, debrief ready
                    v.literal("abandoned"),   // user left mid-session
                  ),
    totalScore:   v.optional(v.number()),    // 0–100, set on completion
    startedAt:    v.optional(v.number()),    // Date.now() when Q1 submitted
    completedAt:  v.optional(v.number()),    // Date.now() when last Q submitted
    createdAt:    v.number(),
  })
    .index("by_userId", ["userId"])
    .index("by_userId_status", ["userId", "status"]),

   //------MESSAGES ----
  // One row per question and answers exchange inside a session
  messages: defineTable({
    sessionId:    v.id("sessions"),
    questionNumber: v.number(),          // 1–7, order within session

    // AI-generated question
    question:     v.string(),
    questionTag:  v.string(),            // e.g. "Behavioral · Teamwork"

    // User's answer — optional until they submit
    answer:       v.optional(v.string()),
    wordCount:    v.optional(v.number()),
    skipped:      v.optional(v.boolean()),

    // Per-answer scores — set after Groq scores the answer
    relevance:    v.optional(v.number()),   // 0–10
    clarity:      v.optional(v.number()),   // 0–10
    depth:        v.optional(v.number()),   // 0–10

    // Raw AI feedback for this specific answer
    feedback:     v.optional(v.string()),

    answeredAt:   v.optional(v.number()),   // Date.now() when submitted
    createdAt:    v.number(),
  })
    .index("by_sessionId", ["sessionId"])
    .index("by_sessionId_questionNumber", ["sessionId", "questionNumber"]),


  // ── DEBRIEFS ───────────────────────────────────────────────────
  // One row per completed session — generated by Groq after last answer
  debriefs: defineTable({
    sessionId:    v.id("sessions"),         // one-to-one with sessions
    userId:       v.id("users"),

    // the Overall total scoring
    overallScore:   v.number(),             
    relevanceAvg:   v.number(),          
    clarityAvg:     v.number(),
    depthAvg:       v.number(),

            // AI-generated feedback arrays
            strengths:      v.array(v.string()),    // what the user did well
            improvements:   v.array(v.string()),    // where to improve
            studyTopics:    v.array(v.string()),    // recommended study topics

    // This is grade accorded at the end
    grade:        v.union(
                    v.literal("Excellent"),
                    v.literal("Good"),
                    v.literal("Fair"),
                    v.literal("Needs Work"),
                  ),

    createdAt:    v.number(),
  })
    .index("by_sessionId", ["sessionId"])
    .index("by_userId", ["userId"]),

});